#!/bin/sh
### BEGIN INIT INFO
# Short-Description: Start/stop the whole application
### END INIT INFO

case "$1" in
    start)
	echo -n "Starting $DESC: "
	            # Démarrage de mysql 
                        		ll/etc/init.d/mysql start 
            	    if [ ${?} -ne 0 ] ; then
		exit ${?}
	    fi
            echo "----"
	            # Démarrage de sphinx 
                        		ll/etc/init.d/searchd start 
            	    if [ ${?} -ne 0 ] ; then
		exit ${?}
	    fi
            echo "----"
		
	;;

    stop) 
		    # Arret de mysql 
                        		ll/etc/init.d/mysql stop 
                RCODE=${?}
		if [ ${RCODE} -ne 0 ]; then
		    exit ${RCODE}
		fi
                        echo "----"	    
		    # Arret de sphinx 
                        		ll/etc/init.d/searchd stop 
                RCODE=${?}
		if [ ${RCODE} -ne 0 ]; then
		    exit ${RCODE}
		fi
                        echo "----"	    
		;;
		
    restart) 
		    # Redemarrage de mysql 
                        		ll/etc/init.d/mysql restart 
                RCODE=${?}
		if [ ${RCODE} -ne 0 ]; then
		    exit ${RCODE}
		fi
            	    echo "----"
		    # Redemarrage de sphinx 
                        		ll/etc/init.d/searchd restart 
                RCODE=${?}
		if [ ${RCODE} -ne 0 ]; then
		    exit ${RCODE}
		fi
            	    echo "----"
		;;

    reload) 
            # Redemarrage de mysql 
                                ll/etc/init.d/mysql reload 
                RCODE=${?}
        if [ ${RCODE} -ne 0 ]; then
            exit ${RCODE}
        fi
                    echo "----"
            # Redemarrage de sphinx 
                                ll/etc/init.d/searchd reload 
                RCODE=${?}
        if [ ${RCODE} -ne 0 ]; then
            exit ${RCODE}
        fi
                    echo "----"
        ;;

    status)
	            # Status de mysql 
                                        ll/etc/init.d/mysql status 
                RCODE=${?}
		if [ ${RCODE} -ne 0 ]; then
		    exit ${RCODE}
		fi
	    	    echo "----"
	            # Status de sphinx 
                                        ll/etc/init.d/searchd status 
                RCODE=${?}
		if [ ${RCODE} -ne 0 ]; then
		    exit ${RCODE}
		fi
	    	    echo "----"
		;;

    *)
        # parametre invalide
	echo "usage: $0 ( start | stop | restart | status | help )"
	cat <<EOF

   start   - demarrage de mysql, sphinx 
   stop    - arret de mysql, sphinx 
   restart - redemarrage de  mysql, sphinx 
   status  - état de  mysql, sphinx 
   help    - cette page

EOF
	;;
esac

exit 0
